{
 "title": "New dashboard",
 "time": { "from": "-043910-09-06T06:03:22.268Z", "to": "+047959-08-07T06:03:22.268Z" },
 "panels": [
  {
   "title": "device connection",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "[\n    {\n        \"timestamp\":1738368000000,\n        \"connected_smartphones\":30,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368060000,\n        \"connected_smartphones\":31,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368120000,\n        \"connected_smartphones\":32,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368180000,\n        \"connected_smartphones\":33,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368240000,\n        \"connected_smartphones\":34,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368300000,\n        \"connected_smartphones\":35,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368360000,\n        \"connected_smartphones\":36,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368420000,\n        \"connected_smartphones\":37,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368480000,\n        \"connected_smartphones\":38,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368540000,\n        \"connected_smartphones\":39,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368600000,\n        \"connected_smartphones\":30,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368660000,\n        \"connected_smartphones\":31,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368720000,\n        \"connected_smartphones\":32,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368780000,\n        \"connected_smartphones\":33,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368840000,\n        \"connected_smartphones\":34,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368900000,\n        \"connected_smartphones\":35,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368960000,\n        \"connected_smartphones\":36,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369020000,\n        \"connected_smartphones\":37,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369080000,\n        \"connected_smartphones\":38,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369140000,\n        \"connected_smartphones\":39,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369200000,\n        \"connected_smartphones\":30,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369260000,\n        \"connected_smartphones\":31,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369320000,\n        \"connected_smartphones\":32,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369380000,\n        \"connected_smartphones\":33,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369440000,\n        \"connected_smartphones\":34,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369500000,\n        \"connected_smartphones\":35,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369560000,\n        \"connected_smartphones\":36,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369620000,\n        \"connected_smartphones\":37,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369680000,\n        \"connected_smartphones\":38,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369740000,\n        \"connected_smartphones\":39,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369800000,\n        \"connected_smartphones\":30,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369860000,\n        \"connected_smartphones\":31,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369920000,\n        \"connected_smartphones\":32,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369980000,\n        \"connected_smartphones\":33,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370040000,\n        \"connected_smartphones\":34,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370100000,\n        \"connected_smartphones\":35,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370160000,\n        \"connected_smartphones\":36,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370220000,\n        \"connected_smartphones\":37,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370280000,\n        \"connected_smartphones\":38,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370340000,\n        \"connected_smartphones\":39,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370400000,\n        \"connected_smartphones\":30,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370460000,\n        \"connected_smartphones\":31,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370520000,\n        \"connected_smartphones\":32,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370580000,\n        \"connected_smartphones\":33,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370640000,\n        \"connected_smartphones\":34,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370700000,\n        \"connected_smartphones\":35,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370760000,\n        \"connected_smartphones\":36,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370820000,\n        \"connected_smartphones\":37,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370880000,\n        \"connected_smartphones\":38,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370940000,\n        \"connected_smartphones\":39,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    }\n]",
     "source": "inline",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "System Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT signal_strength\r\nFROM system_status\r\nORDER BY timestamp DESC\r\nLIMIT 1;\r\n \r\n\r\n"
    },
    {
     "dataset": "dashboard",
     "rawSql": " SELECT alert_queue\r\nFROM system_status\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Network usuage",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "data": "[\n    {\n        \"timestamp\":1738368000000,\n        \"bandwidth_usage_mbps\":50,\n        \"active_devices\":10,\n        \"latency_ms\":20\n    },\n    {\n        \"timestamp\":1738368060000,\n        \"bandwidth_usage_mbps\":51,\n        \"active_devices\":11,\n        \"latency_ms\":21\n    },\n    {\n        \"timestamp\":1738368120000,\n        \"bandwidth_usage_mbps\":52,\n        \"active_devices\":12,\n        \"latency_ms\":22\n    },\n    {\n        \"timestamp\":1738368180000,\n        \"bandwidth_usage_mbps\":53,\n        \"active_devices\":13,\n        \"latency_ms\":23\n    },\n    {\n        \"timestamp\":1738368240000,\n        \"bandwidth_usage_mbps\":54,\n        \"active_devices\":14,\n        \"latency_ms\":24\n    },\n    {\n        \"timestamp\":1738368300000,\n        \"bandwidth_usage_mbps\":55,\n        \"active_devices\":10,\n        \"latency_ms\":25\n    },\n    {\n        \"timestamp\":1738368360000,\n        \"bandwidth_usage_mbps\":56,\n        \"active_devices\":11,\n        \"latency_ms\":26\n    },\n    {\n        \"timestamp\":1738368420000,\n        \"bandwidth_usage_mbps\":57,\n        \"active_devices\":12,\n        \"latency_ms\":20\n    },\n    {\n        \"timestamp\":1738368480000,\n        \"bandwidth_usage_mbps\":58,\n        \"active_devices\":13,\n        \"latency_ms\":21\n    },\n    {\n        \"timestamp\":1738368540000,\n        \"bandwidth_usage_mbps\":59,\n        \"active_devices\":14,\n        \"latency_ms\":22\n    },\n    {\n        \"timestamp\":1738368600000,\n        \"bandwidth_usage_mbps\":50,\n        \"active_devices\":10,\n        \"latency_ms\":23\n    },\n    {\n        \"timestamp\":1738368660000,\n        \"bandwidth_usage_mbps\":51,\n        \"active_devices\":11,\n        \"latency_ms\":24\n    },\n    {\n        \"timestamp\":1738368720000,\n        \"bandwidth_usage_mbps\":52,\n        \"active_devices\":12,\n        \"latency_ms\":25\n    },\n    {\n        \"timestamp\":1738368780000,\n        \"bandwidth_usage_mbps\":53,\n        \"active_devices\":13,\n        \"latency_ms\":26\n    },\n    {\n        \"timestamp\":1738368840000,\n        \"bandwidth_usage_mbps\":54,\n        \"active_devices\":14,\n        \"latency_ms\":20\n    },\n    {\n        \"timestamp\":1738368900000,\n        \"bandwidth_usage_mbps\":55,\n        \"active_devices\":10,\n        \"latency_ms\":21\n    },\n    {\n        \"timestamp\":1738368960000,\n        \"bandwidth_usage_mbps\":56,\n        \"active_devices\":11,\n        \"latency_ms\":22\n    },\n    {\n        \"timestamp\":1738369020000,\n        \"bandwidth_usage_mbps\":57,\n        \"active_devices\":12,\n        \"latency_ms\":23\n    },\n    {\n        \"timestamp\":1738369080000,\n        \"bandwidth_usage_mbps\":58,\n        \"active_devices\":13,\n        \"latency_ms\":24\n    },\n    {\n        \"timestamp\":1738369140000,\n        \"bandwidth_usage_mbps\":59,\n        \"active_devices\":14,\n        \"latency_ms\":25\n    },\n    {\n        \"timestamp\":1738369200000,\n        \"bandwidth_usage_mbps\":50,\n        \"active_devices\":10,\n        \"latency_ms\":26\n    },\n    {\n        \"timestamp\":1738369260000,\n        \"bandwidth_usage_mbps\":51,\n        \"active_devices\":11,\n        \"latency_ms\":20\n    },\n    {\n        \"timestamp\":1738369320000,\n        \"bandwidth_usage_mbps\":52,\n        \"active_devices\":12,\n        \"latency_ms\":21\n    },\n    {\n        \"timestamp\":1738369380000,\n        \"bandwidth_usage_mbps\":53,\n        \"active_devices\":13,\n        \"latency_ms\":22\n    },\n    {\n        \"timestamp\":1738369440000,\n        \"bandwidth_usage_mbps\":54,\n        \"active_devices\":14,\n        \"latency_ms\":23\n    },\n    {\n        \"timestamp\":1738369500000,\n        \"bandwidth_usage_mbps\":55,\n        \"active_devices\":10,\n        \"latency_ms\":24\n    },\n    {\n        \"timestamp\":1738369560000,\n        \"bandwidth_usage_mbps\":56,\n        \"active_devices\":11,\n        \"latency_ms\":25\n    },\n    {\n        \"timestamp\":1738369620000,\n        \"bandwidth_usage_mbps\":57,\n        \"active_devices\":12,\n        \"latency_ms\":26\n    },\n    {\n        \"timestamp\":1738369680000,\n        \"bandwidth_usage_mbps\":58,\n        \"active_devices\":13,\n        \"latency_ms\":20\n    },\n    {\n        \"timestamp\":1738369740000,\n        \"bandwidth_usage_mbps\":59,\n        \"active_devices\":14,\n        \"latency_ms\":21\n    },\n    {\n        \"timestamp\":1738369800000,\n        \"bandwidth_usage_mbps\":50,\n        \"active_devices\":10,\n        \"latency_ms\":22\n    },\n    {\n        \"timestamp\":1738369860000,\n        \"bandwidth_usage_mbps\":51,\n        \"active_devices\":11,\n        \"latency_ms\":23\n    },\n    {\n        \"timestamp\":1738369920000,\n        \"bandwidth_usage_mbps\":52,\n        \"active_devices\":12,\n        \"latency_ms\":24\n    },\n    {\n        \"timestamp\":1738369980000,\n        \"bandwidth_usage_mbps\":53,\n        \"active_devices\":13,\n        \"latency_ms\":25\n    },\n    {\n        \"timestamp\":1738370040000,\n        \"bandwidth_usage_mbps\":54,\n        \"active_devices\":14,\n        \"latency_ms\":26\n    },\n    {\n        \"timestamp\":1738370100000,\n        \"bandwidth_usage_mbps\":55,\n        \"active_devices\":10,\n        \"latency_ms\":20\n    },\n    {\n        \"timestamp\":1738370160000,\n        \"bandwidth_usage_mbps\":56,\n        \"active_devices\":11,\n        \"latency_ms\":21\n    },\n    {\n        \"timestamp\":1738370220000,\n        \"bandwidth_usage_mbps\":57,\n        \"active_devices\":12,\n        \"latency_ms\":22\n    },\n    {\n        \"timestamp\":1738370280000,\n        \"bandwidth_usage_mbps\":58,\n        \"active_devices\":13,\n        \"latency_ms\":23\n    },\n    {\n        \"timestamp\":1738370340000,\n        \"bandwidth_usage_mbps\":59,\n        \"active_devices\":14,\n        \"latency_ms\":24\n    },\n    {\n        \"timestamp\":1738370400000,\n        \"bandwidth_usage_mbps\":50,\n        \"active_devices\":10,\n        \"latency_ms\":25\n    },\n    {\n        \"timestamp\":1738370460000,\n        \"bandwidth_usage_mbps\":51,\n        \"active_devices\":11,\n        \"latency_ms\":26\n    },\n    {\n        \"timestamp\":1738370520000,\n        \"bandwidth_usage_mbps\":52,\n        \"active_devices\":12,\n        \"latency_ms\":20\n    },\n    {\n        \"timestamp\":1738370580000,\n        \"bandwidth_usage_mbps\":53,\n        \"active_devices\":13,\n        \"latency_ms\":21\n    },\n    {\n        \"timestamp\":1738370640000,\n        \"bandwidth_usage_mbps\":54,\n        \"active_devices\":14,\n        \"latency_ms\":22\n    },\n    {\n        \"timestamp\":1738370700000,\n        \"bandwidth_usage_mbps\":55,\n        \"active_devices\":10,\n        \"latency_ms\":23\n    },\n    {\n        \"timestamp\":1738370760000,\n        \"bandwidth_usage_mbps\":56,\n        \"active_devices\":11,\n        \"latency_ms\":24\n    },\n    {\n        \"timestamp\":1738370820000,\n        \"bandwidth_usage_mbps\":57,\n        \"active_devices\":12,\n        \"latency_ms\":25\n    },\n    {\n        \"timestamp\":1738370880000,\n        \"bandwidth_usage_mbps\":58,\n        \"active_devices\":13,\n        \"latency_ms\":26\n    },\n    {\n        \"timestamp\":1738370940000,\n        \"bandwidth_usage_mbps\":59,\n        \"active_devices\":14,\n        \"latency_ms\":20\n    }\n]",
     "source": "inline",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Response time alert",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT DATE(response_start_time) AS date, AVG(response_duration) AS avg_response_time\r\nFROM incident_response_times\r\nGROUP BY DATE(response_start_time);\r\n"
    }
   ]
  },
  {
   "title": " Resource Allocation",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT resource_type, status, eta\r\nFROM resources;\r\n"
    }
   ]
  },
  {
   "title": "alerts",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "data": "[\n    {\n        \"timestamp\":1738368000000,\n        \"alert_type\":\"Network Down\",\n        \"severity\":\"Critical\",\n        \"location\":\"Region A\"\n    },\n    {\n        \"timestamp\":1738371600000,\n        \"alert_type\":\"High Latency\",\n        \"severity\":\"High\",\n        \"location\":\"Region B\"\n    },\n    {\n        \"timestamp\":1738375200000,\n        \"alert_type\":\"Unauthorized Access\",\n        \"severity\":\"Medium\",\n        \"location\":\"Region C\"\n    },\n    {\n        \"timestamp\":1738378800000,\n        \"alert_type\":\"Device Overload\",\n        \"severity\":\"Low\",\n        \"location\":\"Region D\"\n    },\n    {\n        \"timestamp\":1738382400000,\n        \"alert_type\":\"Network Down\",\n        \"severity\":\"Critical\",\n        \"location\":\"Region A\"\n    },\n    {\n        \"timestamp\":1738386000000,\n        \"alert_type\":\"High Latency\",\n        \"severity\":\"High\",\n        \"location\":\"Region B\"\n    },\n    {\n        \"timestamp\":1738389600000,\n        \"alert_type\":\"Unauthorized Access\",\n        \"severity\":\"Medium\",\n        \"location\":\"Region C\"\n    },\n    {\n        \"timestamp\":1738393200000,\n        \"alert_type\":\"Device Overload\",\n        \"severity\":\"Low\",\n        \"location\":\"Region D\"\n    },\n    {\n        \"timestamp\":1738396800000,\n        \"alert_type\":\"Data Breach\",\n        \"severity\":\"Critical\",\n        \"location\":\"Region E\"\n    },\n    {\n        \"timestamp\":1738400400000,\n        \"alert_type\":\"Service Restored\",\n        \"severity\":\"Info\",\n        \"location\":\"HQ\"\n    }\n]",
     "source": "inline",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Incident Trends ",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT date, alert_type, alert_count\r\nFROM analytics;\r\n"
    }
   ]
  },
  {
   "title": "Geolocation",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "data": "[\n    {\n        \"timestamp\":1738368000000,\n        \"connected_smartphones\":30,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368060000,\n        \"connected_smartphones\":31,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368120000,\n        \"connected_smartphones\":32,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368180000,\n        \"connected_smartphones\":33,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368240000,\n        \"connected_smartphones\":34,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368300000,\n        \"connected_smartphones\":35,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368360000,\n        \"connected_smartphones\":36,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368420000,\n        \"connected_smartphones\":37,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368480000,\n        \"connected_smartphones\":38,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368540000,\n        \"connected_smartphones\":39,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368600000,\n        \"connected_smartphones\":30,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368660000,\n        \"connected_smartphones\":31,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368720000,\n        \"connected_smartphones\":32,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368780000,\n        \"connected_smartphones\":33,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368840000,\n        \"connected_smartphones\":34,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368900000,\n        \"connected_smartphones\":35,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738368960000,\n        \"connected_smartphones\":36,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369020000,\n        \"connected_smartphones\":37,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369080000,\n        \"connected_smartphones\":38,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369140000,\n        \"connected_smartphones\":39,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369200000,\n        \"connected_smartphones\":30,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369260000,\n        \"connected_smartphones\":31,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369320000,\n        \"connected_smartphones\":32,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369380000,\n        \"connected_smartphones\":33,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369440000,\n        \"connected_smartphones\":34,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369500000,\n        \"connected_smartphones\":35,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369560000,\n        \"connected_smartphones\":36,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369620000,\n        \"connected_smartphones\":37,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369680000,\n        \"connected_smartphones\":38,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369740000,\n        \"connected_smartphones\":39,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369800000,\n        \"connected_smartphones\":30,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369860000,\n        \"connected_smartphones\":31,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369920000,\n        \"connected_smartphones\":32,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738369980000,\n        \"connected_smartphones\":33,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370040000,\n        \"connected_smartphones\":34,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370100000,\n        \"connected_smartphones\":35,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370160000,\n        \"connected_smartphones\":36,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370220000,\n        \"connected_smartphones\":37,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370280000,\n        \"connected_smartphones\":38,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370340000,\n        \"connected_smartphones\":39,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370400000,\n        \"connected_smartphones\":30,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370460000,\n        \"connected_smartphones\":31,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370520000,\n        \"connected_smartphones\":32,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370580000,\n        \"connected_smartphones\":33,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370640000,\n        \"connected_smartphones\":34,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370700000,\n        \"connected_smartphones\":35,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370760000,\n        \"connected_smartphones\":36,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370820000,\n        \"connected_smartphones\":37,\n        \"connected_mesh_nodes\":7,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370880000,\n        \"connected_smartphones\":38,\n        \"connected_mesh_nodes\":5,\n        \"connected_satellites\":1\n    },\n    {\n        \"timestamp\":1738370940000,\n        \"connected_smartphones\":39,\n        \"connected_mesh_nodes\":6,\n        \"connected_satellites\":1\n    }\n]",
     "source": "inline",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Responder Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT status, COUNT(*) AS count\r\nFROM responders\r\nGROUP BY status;\r\n"
    }
   ]
  },
  {
   "title": "Communication log",
   "type": "logs",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, message, responder_name, status\r\nFROM communications;\r\n"
    }
   ]
  },
  {
   "title": "real time",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 29 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT alert_id, alert_time, signal_type, severity_level, sender_name, verification_status\r\nFROM sigalert;\r\n"
    }
   ]
  }
 ]
}